-- ***************************************
-- VCLua form export
-- Copyright (C) 2013-2026 Hi-Project Ltd.
-- ***************************************

local model = require "model"
local serializer = require "serializer"
local exportWizard = require "dialogs.export_wizard"
local VCL = require "vcl.core"

local M = {}

local function pathDir(fileName)
  fileName = tostring(fileName or "")
  local dir = fileName:match("^(.*[/\\])[^/\\]*$")
  return dir and dir ~= "" and dir or "dev/"
end

local function pathBase(fileName)
  fileName = tostring(fileName or "")
  return fileName:match("([^/\\]+)$") or fileName
end

local function replaceExtension(fileName, extension)
  fileName = tostring(fileName or "")
  local base = fileName:gsub("%.[^./\\]+$", "")
  if base == fileName and fileName == "" then base = "form1" end
  return base .. extension
end

local function fileExists(fileName)
  local file = io.open(fileName, "rb")
  if not file then return false end
  file:close()
  return true
end

local function writeTextFile(fileName, content)
  local file, err = io.open(fileName, "wb")
  if not file then return false, err end
  local ok, writeErr = file:write(content)
  file:close()
  if not ok then return false, writeErr end
  return true
end

local function luaQuote(value)
  return string.format("%q", tostring(value or ""))
end

local function moduleNameFromFile(fileName)
  return pathBase(fileName):gsub("%.lua$", ""):gsub("[^%w_]", "_")
end


local function resolveAssetPath(sourceFile, assetFile)
  if fileExists(assetFile) then return assetFile end
  local relative = pathDir(sourceFile) .. assetFile
  if fileExists(relative) then return relative end
  return nil
end

local function pictureStreamHex(fileName)
  local image = VCL.Image()
  local stream = VCL.MemoryStream()

  local ok, err = pcall(function()
    image.Picture:LoadFromFile(fileName)
    image.Picture:SaveToStream(stream)
  end)

  if not ok then
    pcall(function() stream:Free() end)
    pcall(function() image:Free() end)
    return nil, err
  end

  stream.Position = 0
  local parts = {}
  while stream.Position < stream.Size do
    parts[#parts + 1] = string.format("%02X", stream:ReadByte())
  end

  stream:Free()
  image:Free()
  return table.concat(parts)
end

local function fileHex(fileName)
  local file, err = io.open(fileName, "rb")
  if not file then return nil, err end
  local data = file:read("*a")
  file:close()
  local parts = {}
  for i = 1, #data do
    parts[#parts + 1] = string.format("%02X", data:byte(i))
  end
  return table.concat(parts)
end

local function appendHexResource(lines, key, hexData)
  lines[#lines + 1] = "    [" .. luaQuote(key) .. "] = [["
  local position = 1
  while position <= #hexData do
    lines[#lines + 1] = hexData:sub(position, position + 95)
    position = position + 96
  end
  lines[#lines + 1] = "]],"
end

local function resourceModuleSource(project, sourceFile)
  local imageFiles = serializer.collectImageFiles(project)
  local iconFiles = serializer.collectIconFiles and serializer.collectIconFiles(project) or {}
  local lines = {
    "-- Generated by VCLua Form Editor. Do not edit this file manually.",
    "-- Re-exporting the design may overwrite it.",
    "",
    "return {",
    "  images = {",
  }

  for _, assetFile in ipairs(imageFiles) do
    local resolved = resolveAssetPath(sourceFile, assetFile)
    if not resolved then
      return nil, "Image file not found: " .. tostring(assetFile)
    end

    local hexData, err = pictureStreamHex(resolved)
    if not hexData then
      return nil, "Cannot convert image " .. tostring(assetFile) .. ": " .. tostring(err)
    end

    appendHexResource(lines, assetFile, hexData)
  end

  lines[#lines + 1] = "  },"
  lines[#lines + 1] = "  icons = {"

  for _, assetFile in ipairs(iconFiles) do
    local resolved = resolveAssetPath(sourceFile, assetFile)
    if not resolved then
      return nil, "Icon file not found: " .. tostring(assetFile)
    end

    local hexData, err = fileHex(resolved)
    if not hexData then
      return nil, "Cannot read icon " .. tostring(assetFile) .. ": " .. tostring(err)
    end

    appendHexResource(lines, assetFile, hexData)
  end

  lines[#lines + 1] = "  },"
  lines[#lines + 1] = "}"
  lines[#lines + 1] = ""
  return table.concat(lines, "\n")
end

local function eventSkeletonSource(project)
  local actions = {}
  local menuItems = {}
  local controls = {}
  local seen = {}
  local buttonClasses = {
    Button = true,
    SpeedButton = true,
    BitBtn = true,
    ToolButton = true,
    EditButton = true,
  }

  local function add(target, name, eventName)
    name = tostring(name or "")
    if name == "" then return end
    local key = name .. ":" .. eventName
    if seen[key] then return end
    seen[key] = true
    target[#target + 1] = { name = name, eventName = eventName }
  end

  local function scanMenuItems(items)
    for _, item in ipairs(items or {}) do
      if type(item) == "table" then
        local caption = tostring(item.Caption or item.caption or "")
        if caption ~= "-" and (not item.Action or item.Action == "") then
          add(menuItems, item.Name or item.name, "OnClick")
        end
        scanMenuItems(item.Items or item.items)
      end
    end
  end

  local function scanNode(node)
    if type(node) ~= "table" then return end
    local props = type(node.props) == "table" and node.props or {}
    local className = tostring(node.class or "")

    if className == "ActionList" then
      for _, action in ipairs(props.Actions or {}) do
        add(actions, action.Name or action.name, "OnExecute")
      end
    elseif className == "MainMenu" or className == "PopupMenu" then
      scanMenuItems(props.MenuItems)
    elseif buttonClasses[className] and (not props.Action or props.Action == "") then
      add(controls, node.name, "OnClick")
    end

    for _, child in ipairs(node.items or {}) do scanNode(child) end
  end

  scanNode(model.getRoot(project))

  local lines = {
    "local M = {}",
    "",
    "function M.bind(ui)",
  }

  local function appendHandlers(entries)
    for _, entry in ipairs(entries) do
      lines[#lines + 1] = "  if ui[" .. luaQuote(entry.name) .. "] then"
      lines[#lines + 1] = "    ui[" .. luaQuote(entry.name) .. "]." .. entry.eventName .. " = function(sender)"
      lines[#lines + 1] = "    end"
      lines[#lines + 1] = "  end"
      lines[#lines + 1] = ""
    end
  end

  appendHandlers(actions)
  appendHandlers(menuItems)
  appendHandlers(controls)

  lines[#lines + 1] = "  return ui"
  lines[#lines + 1] = "end"
  lines[#lines + 1] = ""
  lines[#lines + 1] = "return M"
  lines[#lines + 1] = ""
  return table.concat(lines, "\n")
end

local function runnerSource(config, rootName)
  local formModule = moduleNameFromFile(config.outputFile)
  local eventsModule = moduleNameFromFile(config.eventsFile)
  local derivedEvents = eventsModule == formModule .. "_events"
  local lines = {
    "local baseForm = " .. luaQuote(formModule),
  }

  if config.generateEvents then
    if derivedEvents then
      lines[#lines + 1] = "local baseFormEvents = baseForm .. \"_events\""
    else
      lines[#lines + 1] = "local baseFormEvents = " .. luaQuote(eventsModule)
    end
  end

  lines[#lines + 1] = ""
  lines[#lines + 1] = [=[local source = debug.getinfo(1, "S").source:gsub("^@", "")]=]
  lines[#lines + 1] = [=[local scriptDir = source:match("^(.*[/\\])") or ""]=]
  lines[#lines + 1] = ""
  lines[#lines + 1] = 'package.path = package.path ..'
  lines[#lines + 1] = '  ";" .. scriptDir .. "?.lua" ..'
  lines[#lines + 1] = '  ";" .. scriptDir .. "vcl/?.lua"'
  lines[#lines + 1] = ""
  lines[#lines + 1] = 'local VCL = require "vcl"'
  lines[#lines + 1] = 'VCL.AddPackagePath(scriptDir)'
  lines[#lines + 1] = 'local app = VCL.InitRuntime()'
  lines[#lines + 1] = ""

  if config.generateEvents then
    lines[#lines + 1] = "local ui = VCL.LoadFormApp(baseForm, { eventsModule = baseFormEvents })"
  else
    lines[#lines + 1] = "local ui = VCL.LoadFormApp(baseForm, { bindEvents = false })"
  end

  lines[#lines + 1] = "ui[" .. luaQuote(rootName) .. "]:ShowModal()"
  lines[#lines + 1] = ""
  return table.concat(lines, "\n")
end

function M.run(options)
  options = options or {}
  local project = assert(options.project, "project is required")
  local showMessage = options.showMessage or function() end
  local setStatus = options.setStatus or function() end
  local sourceFile = options.currentFileName or options.defaultFormFile or "test_form.vclform"
  local base = pathBase(sourceFile):gsub("%.vclform$", ""):gsub("[^%w_]", "_")
  if base == "" then base = "form1" end

  local config = exportWizard.open({ showMessage = showMessage }, {
    modeIndex = 0,
    moduleName = base,
    outputFile = replaceExtension(sourceFile, ".lua"),
    jsonFile = replaceExtension(sourceFile, ".json"),
    eventsFile = replaceExtension(sourceFile, "_events.lua"),
    runnerFile = pathDir(sourceFile) .. "run.lua",
    embedResources = true,
  })
  if not config then return false end

  if options.prepare then options.prepare() end
  local exported = {}
  local skipped = {}

  if config.exportLua then
    local resourcesModule
    if config.embedResources then
      local source, err = resourceModuleSource(project, sourceFile)
      if not source then showMessage("Resource export failed: " .. tostring(err)); return false end
      local ok, writeErr = writeTextFile(config.resourcesFile, source)
      if not ok then showMessage("Resource export failed: " .. tostring(writeErr)); return false end
      resourcesModule = moduleNameFromFile(config.resourcesFile)
      exported[#exported + 1] = config.resourcesFile
    end

    local ok, err = serializer.exportLuaModule(project, config.outputFile, config.moduleName, {
      embedResources = config.embedResources,
      resourcesModule = resourcesModule,
    })
    if not ok then showMessage("Lua export failed: " .. tostring(err)); return false end
    exported[#exported + 1] = config.outputFile
  end

  if config.exportJson then
    local ok, err = serializer.saveJson(project, config.jsonFile)
    if not ok then showMessage("JSON export failed: " .. tostring(err)); return false end
    exported[#exported + 1] = config.jsonFile
  end

  if config.generateEvents then
    if fileExists(config.eventsFile) then
      skipped[#skipped + 1] = config.eventsFile
    else
      local ok, err = writeTextFile(config.eventsFile, eventSkeletonSource(project))
      if not ok then showMessage("Event skeleton export failed: " .. tostring(err)); return false end
      exported[#exported + 1] = config.eventsFile
    end
  end

  if config.generateRunner then
    if fileExists(config.runnerFile) then
      skipped[#skipped + 1] = config.runnerFile
    else
      local root = model.getRoot(project)
      local rootName = root and root.name or "Form1"
      local ok, err = writeTextFile(config.runnerFile, runnerSource(config, rootName))
      if not ok then showMessage("Runner export failed: " .. tostring(err)); return false end
      exported[#exported + 1] = config.runnerFile
    end
  end

  local parts = {}
  if #exported > 0 then parts[#parts + 1] = "Exported: " .. table.concat(exported, ", ") end
  if #skipped > 0 then parts[#parts + 1] = "Preserved existing: " .. table.concat(skipped, ", ") end
  local message = table.concat(parts, "\n")
  setStatus(parts[1] or "Export completed")
  showMessage(message ~= "" and message or "Export completed")
  return true, config
end

return M
